### ISSUE TITLE
Многопоточная обработка страниц

### ISSUE THREAD

**Issue by SsDp812** [SsDp812/ps-render-v2#3]
Сделать параллельную обработку нескольких страниц в многопоточным режиме.

Выполнять после задачи https://github.com/SsDp812/ps-render-v2/issues/2

**Comment by 2immons** [comment]
Многопоточность, похоже, невозможна из-за того, что WebDriver может работать только с одной вкладкой.
Создание новых экземпляров WebDriver с куками базового WebDriver (чтобы сохранить нажатие кнопок) позволяет работать с несколькими вкладками сразу, но выигрыша по времени нет из-за постоянного открытия браузера.

**Comment by SsDp812** [comment]
Пока закрываем (возможно потом вернемся к этому)
