### ISSUE TITLE
Сделать скрол страниц вниз

### ISSUE THREAD

**Issue by SsDp812** [SsDp812/ps-render-v2#4]
Обрабатывать не 1 страницу категории, а скролить вниз (возможно нажимать кнопку показать еще)

**Comment by 2immons** [comment]
Браузер зависает если кликать "показать еще", когда уже 60+ страница.
Видимо, нужно сохранять результаты с каждой страницы, переходить на новую, заново сохранять и так далее, чтобы не лагало.
